import{test}from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{build}from'esbuild';import{JSDOM}from'jsdom';
test('all eleven UI catalogs include every key and preserve interpolation values',()=>{
 const c=JSON.parse(readFileSync('public/locales.json'));assert.deepEqual(Object.keys(c).sort(),['en','zh-Hans','zh-Hant','ja','ko','ar','es','fr','de','ru','vi'].sort());
 for(const [lang,strings]of Object.entries(c))for(const [key,source]of Object.entries(c.en)){assert.equal(typeof strings[key],'string',lang+': '+key);assert.ok(strings[key].trim(),lang+': '+key);assert.deepEqual((strings[key].match(/\{\w+\}/g)||[]).sort(),(source.match(/\{\w+\}/g)||[]).sort(),lang+': '+key)}
 for(const lang of Object.keys(c).filter(x=>x!=='en'))for(const key of ['Library','Profile','Discuss paragraph','Your private notes are saved.','Only me'])assert.notEqual(c[lang][key],c.en[key],lang+': untranslated '+key);
});
test('paragraph controls preserve text selection and stable duplicate paragraph anchors',async()=>{
 const {outputFiles}=await build({entryPoints:['src/paragraphs.ts'],bundle:true,platform:'node',format:'esm',write:false});const {paragraphActions}=await import('data:text/javascript;base64,'+Buffer.from(outputFiles[0].text).toString('base64'));
 const dom=new JSDOM('<main><p>One useful paragraph about the physics of quantum entanglement.</p><p>One useful paragraph about the physics of quantum entanglement.</p><blockquote><p>A second passage about a figure with enough detail to discuss.</p></blockquote><p>Short</p><div>A Mathpix Markdown paragraph uses a plain div but should have a discussion action too.</div></main>');globalThis.document=dom.window.document;const root=document.querySelector('main'),calls=[];
 try{paragraphActions(root,'Discuss paragraph',(...args)=>calls.push(args));const buttons=[...root.querySelectorAll('button')];assert.equal(buttons.length,4);const ids=[...root.querySelectorAll('[data-paragraph]')].map(x=>x.dataset.paragraph);assert.notEqual(ids[0],ids[1]);assert.match(ids[0],/^p-[a-f0-9]+-1$/);assert.match(ids[1],/-2$/);const pointer=new dom.window.Event('pointerdown',{cancelable:true});buttons[0].dispatchEvent(pointer);assert.equal(pointer.defaultPrevented,true);buttons[0].click();assert.equal(calls[0][1],ids[0]);assert.equal(calls[0][0],'One useful paragraph about the physics of quantum entanglement.');assert.equal(buttons[0].getAttribute('aria-label'),'Discuss paragraph');}finally{dom.window.close();delete globalThis.document}
});
