import{test}from'node:test';import assert from'node:assert/strict';import{createHmac,randomUUID}from'node:crypto';import{mkdtempSync,rmSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import{Store}from'../server/store.mjs';import{createStripeBilling,stripeSignature}from'../server/stripe-billing.mjs';import{billingAccount,applyVerifiedPurchase,deleteBillingAccount}from'../server/billing-ledger.mjs';import{quotaSummary}from'../server/subscription-quota.mjs';
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'oi-stripe-')),store=new Store(dir);t.after(()=>{store.close();rmSync(dir,{recursive:true,force:true})});writeFileSync(join(dir,'key'),'sk_test_fixture',{mode:0o600});writeFileSync(join(dir,'hook'),'whsec_fixture',{mode:0o600});const config={origin:'https://onlyideas.invalid',credits:{enabled:true},billing:{enabled:true,quotasEnabled:true,stripe:{portalConfiguration:'bpc_onlyideas',keyFile:join(dir,'key'),webhookSecretFile:join(dir,'hook'),prices:{reader:'price_reader',researcher:'price_researcher',studio:'price_studio'}}}};return{store,config}}
const sign=raw=>{const t=Math.floor(Date.now()/1000);return 't='+t+',v1='+createHmac('sha256','whsec_fixture').update(t+'.').update(raw).digest('hex')};
test('Stripe raw-body signature rejects tampering, stale timestamps and malformed digests',()=>{const raw=Buffer.from('{"exact":"payload"}');stripeSignature(raw,sign(raw),'whsec_fixture');assert.throws(()=>stripeSignature(Buffer.from('{}'),sign(raw),'whsec_fixture'));assert.throws(()=>stripeSignature(raw,sign(raw),'wrong'));assert.throws(()=>stripeSignature(raw,sign(raw),'whsec_fixture',Date.now()+400_000));assert.throws(()=>stripeSignature(raw,'t=bad,v1=a','whsec_fixture'))});
test('PWA checkout fixes the plan price, account binding, seven-day trial and URLs; double click reuses checkout',async t=>{
 const {store,config}=fixture(t),calls=[];let sessions=0;
 const stripe=createStripeBilling(store,config,{transport:async(url,options)=>{const u=new URL(url),v=Object.fromEntries(new URLSearchParams(options.body));calls.push({path:u.pathname,v,headers:options.headers});let data;
  if(u.pathname==='/v1/prices/price_reader')data={id:'price_reader',active:true,livemode:false,currency:'usd',unit_amount:299,recurring:{interval:'month',interval_count:1}};
  else if(u.pathname==='/v1/customers')data={id:'cus_reader'};
  else if(u.pathname==='/v1/checkout/sessions'){sessions++;data={id:'cs_trial',url:'https://checkout.stripe.com/c/pay/test',livemode:false};assert.equal(v['subscription_data[trial_period_days]'],'7');assert.equal(v['line_items[0][price]'],'price_reader');assert.equal(v['subscription_data[metadata][account_token]'],billingAccount(store,'reader'));assert.equal(v.success_url,config.origin+'/?billing=success')}
  else throw Error('Unexpected '+url);return new Response(JSON.stringify(data));}});
 assert.equal(stripe.ready,true);const first=await stripe.checkout({id:'reader'},'reader');assert.deepEqual(await stripe.checkout({id:'reader'},'reader'),first);assert.equal(sessions,1);
 await assert.rejects(stripe.checkout({id:'reader'},'invented'));await assert.rejects(stripe.checkout({id:'reader'},'studio'),/current checkout/);
 assert.ok(calls.every(c=>c.headers['Stripe-Version']==='2024-06-20'));
});
test('only a verified bound invoice grants quotas/credits; refunds revoke once and unrelated app webhooks are ignored',async t=>{
 const {store,config}=fixture(t),accountToken=billingAccount(store,'reader');let refunded=false,bad=false,pending=false;
 store.db.exec('CREATE TABLE billing_stripe_customers(owner TEXT PRIMARY KEY,customer TEXT UNIQUE NOT NULL)');store.db.prepare('INSERT INTO billing_stripe_customers VALUES(?,?)').run('reader','cus_reader');
 const price={id:'price_reader',active:true,livemode:false,currency:'usd',unit_amount:299,recurring:{interval:'month',interval_count:1}},start=Math.floor(Date.now()/1000)-10,end=start+30*86400;
 const sub={id:'sub_reader',customer:'cus_reader',livemode:false,metadata:{app:'onlyideas',account_token:accountToken},status:'active',items:{data:[{quantity:1,price}]}},invoice={id:'in_paid',subscription:'sub_reader',customer:'cus_reader',livemode:false,status:'paid',amount_paid:299,currency:'usd',charge:'ch_paid',lines:{data:[{price:'price_reader',quantity:1,period:{start,end}}]}};
 const stripe=createStripeBilling(store,config,{transport:async(url)=>{const p=new URL(url).pathname;return new Response(JSON.stringify(p.startsWith('/v1/subscriptions/')?sub:p==='/v1/invoices'?{data:pending?[]:[{...invoice,customer:bad?'cus_other':'cus_reader'}]}:p==='/v1/charges/ch_paid'?{customer:'cus_reader',livemode:false,refunded}:{}))}});
 let result=await stripe.verify('sub_reader');assert.equal(applyVerifiedPurchase(store,result.proofs[0],'reader').awarded,200);assert.equal(applyVerifiedPurchase(store,result.proofs[0],'reader').awarded,0);assert.equal(quotaSummary(store,config,'reader').pages,200);
 bad=true;await assert.rejects(stripe.verify('sub_reader'),/ownership/);bad=false;refunded=true;result=await stripe.verify('sub_reader');applyVerifiedPurchase(store,result.proofs[0],'reader');assert.equal(quotaSummary(store,config,'reader').pages,30);
 const raw=Buffer.from(JSON.stringify({livemode:false,type:'customer.subscription.updated',data:{object:{id:'sub_other',metadata:{app:'echomind'}}}}));assert.equal(await stripe.notification({headers:{'stripe-signature':sign(raw)}},raw),null);
 pending=true;assert.equal((await stripe.verify('sub_reader')).proofs.length,0);pending=false;
 deleteBillingAccount(store,'reader');const closed=Buffer.from(JSON.stringify({livemode:false,type:'customer.subscription.updated',data:{object:sub}}));assert.equal(await stripe.notification({headers:{'stripe-signature':sign(closed)}},closed),null);assert.equal(store.db.prepare('SELECT count(*) n FROM billing_subscriptions').get().n,0);
});
