import { useEffect,useRef,useState } from 'react'
import { ArrowUp,Plus,MessageCircle,Trash2,Paperclip,X,FileText } from 'lucide-react'
import { api,post,type Attachment } from './api'
import { request } from './native'
import { t, currentLanguage } from './i18n'
type Card={id:string;title:string;authors:string;summary:string;year:string}
type Message={id:string;role:string;text:string;papers?:Card[];jobId?:string;attachments?:Attachment[]}
type Chat={id:string;title:string}
export function Agent({signedIn,login,notify,openPaper}:{signedIn:boolean;login:()=>void;notify:(s:string)=>void;openPaper:(id:string)=>void}) {
 const [chats,setChats]=useState<Chat[]>([]),[chat,setChat]=useState(''),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[files,setFiles]=useState<Attachment[]>([])
 const end=useRef<HTMLDivElement>(null),picker=useRef<HTMLInputElement>(null),identity=useRef(0)
 const list=()=>api<{chats:Chat[]}>('/chats').then(r=>setChats(r.chats))
 useEffect(()=>{identity.current++;if(signedIn)void list().catch(e=>notify(e.message));else{setChats([]);setMessages([]);setFiles([]);setChat('')}},[signedIn])
 useEffect(()=>{if(!chat)return;let active=true;const update=()=>api<{messages:Message[];pending:{status:string}[];agent:{online:boolean}}>(`/chats/${chat}`).then(r=>{if(active){setMessages(r.messages);setStatus(r.pending[0]?(r.agent.online?r.pending[0].status:'Your request is saved. Waiting for the paper agent…'):'')}}).catch(e=>{if(active)notify(e.message)});void update();const timer=setInterval(update,2500);return()=>{active=false;clearInterval(timer)}},[chat])
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length,status])
 async function upload(selected:FileList|null){
  if(!signedIn){login();return}if(!selected)return
  if(files.length+selected.length>3){notify(t('Attach up to three files.'));return}
  const epoch=identity.current;setUploading(true)
  try{for(const file of Array.from(selected)){if(file.size>20_000_000)throw Error(t('Choose a file smaller than 20 MB.'));const r=await request('/api/attachments',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name)},body:file});const data=await r.json();if(!r.ok)throw Error(data.error);if(epoch===identity.current)setFiles(previous=>previous.some(a=>a.id===data.attachment.id)?previous:[...previous,data.attachment])}}
  catch(e){notify((e as Error).message)}finally{setUploading(false);if(picker.current)picker.current.value=''}
 }
 const send=async(text=draft)=>{if(!signedIn){login();return}if((!text.trim()&&!files.length)||busy||status||uploading)return;setBusy(true);try{let id=chat;if(!id){const r=await post<{chat:Chat}>('/chats',{});id=r.chat.id;setChat(id)}await post(`/chats/${id}/messages`,{text,attachments:files.map(f=>f.id),language:currentLanguage()});setMessages(v=>[...v,{id:crypto.randomUUID(),role:'user',text:text||t('Help me understand these files.'),attachments:files}]);setFiles([]);setDraft('');setStatus(t("Waiting for the paper agent"));await list()}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 const [sharing,setSharing]=useState('shared')
 return <main className="agent-layout">
 <aside className="chat-history"><button className="secondary" onClick={()=>{identity.current++;setChat('');setMessages([]);setStatus('');setFiles([])}}><Plus size={20}/> {t("New conversation")}</button><h2>{t("Conversations")}</h2>{chats.map(c=><div className="history-row" key={c.id}><button className={chat===c.id?'selected':''} onClick={()=>setChat(c.id)}>{c.title==='New conversation'?t(c.title):c.title}</button><button aria-label={t('Delete conversation')} onClick={async()=>{if(!confirm(t('Delete this conversation?')))return;try{await api(`/chats/${c.id}`,{method:'DELETE'});if(chat===c.id){setChat('');setMessages([]);setStatus('')}await list()}catch(e){notify((e as Error).message)}}}><Trash2 size={16}/></button></div>)}</aside>
 <section className="agent-conversation"><div className="agent-messages">
 {!messages.length&&<div className="agent-welcome"><MessageCircle size={36}/><h1>{t("What are you curious about?")}</h1><p>{t("Find a paper. Ask about your files. Follow an idea.")}</p>{['Find open papers about quantum entanglement','Help me find research on language learning'].map(s=><button className="suggestion" key={s} onClick={()=>void send(t(s))}>{t(s)}</button>)}</div>}
 {messages.map(m=><div key={m.id} className={`chat-message ${m.role}`}><strong>{m.role==='user'?t('You'):'OnlyIdeas'}</strong><p>{m.role==='assistant'?t(m.text):m.text}</p>
 {m.attachments?.map(f=><div className="attachment-chip" key={f.id}><FileText size={18}/><span>{f.name}<small>{t(f.state==='ready'?t("Ready"):f.state==='failed'?t("Could not prepare file"):t("Preparing your attachments"))}</small></span>{f.paperId&&<button className="text-button" onClick={()=>openPaper(f.paperId!)}>{t("Open paper")}</button>}</div>)}
 {m.role==='assistant'&&<button className="text-button" onClick={async()=>{const reason=prompt(t('What concerns you about this AI response?'));if(reason)try{await post('/reports',{context:`Agent message ${m.id} in conversation ${chat}`,reason});notify(t('Report sent for review.'))}catch(e){notify((e as Error).message)}}}>{t("Report response")}</button>}
 {m.papers?.map(p=><article className="agent-paper" key={p.id}><span>{p.year} · {t('Open paper')}</span><h3>{p.title}</h3><p>{p.authors}</p><details><summary>{t("Read abstract")}</summary><p>{p.summary}</p></details><label>{t("Visibility")}<select aria-label={t("Paper visibility")} value={sharing} onChange={e=>setSharing(e.target.value)}><option value="shared">{t("Shared reading room")}</option><option value="private">{t("Only me")}</option></select></label><p>{t("Shared papers appear after source and community review. Your chat stays private.")}</p><button className="primary" onClick={async()=>{try{await post(`/chats/${chat}/import`,{paperId:p.id,sharing});notify(t('Paper queued. Follow its conversion in Your requests.'))}catch(e){notify((e as Error).message)}}}>{t("Convert & add")}</button></article>)}</div>)}
 {status&&<p className="agent-progress" role="status">{t(status)}</p>}<div ref={end}/></div>
 <div className="attachment-tray">{files.map(f=><div className="attachment-chip" key={f.id}><FileText size={16}/><span>{f.name}</span><button aria-label={t("Remove attachment")} onClick={()=>setFiles(v=>v.filter(a=>a.id!==f.id))}><X size={16}/></button></div>)}{uploading&&<p role="status">{t("Uploading attachment…")}</p>}</div>
 <form className="chat-composer" onSubmit={e=>{e.preventDefault();void send()}}><input ref={picker} hidden type="file" multiple accept=".pdf,.docx,.png,.jpg,.jpeg,.webp,.txt,.md,.mmd,.csv,.json,.tex" onChange={e=>void upload(e.target.files)}/><button type="button" className="icon-button" aria-label={t("Attach files")} disabled={uploading||files.length>=3} onClick={()=>signedIn?picker.current?.click():login()}><Paperclip size={22}/></button><textarea aria-label={t("Message the paper agent")} placeholder={t("Ask a question or attach a file…")} rows={2} maxLength={4000} value={draft} onChange={e=>setDraft(e.target.value)}/><button className="primary" aria-label={t("Send message")} disabled={busy||uploading||!!status||(!draft.trim()&&!files.length)}><ArrowUp size={24}/></button></form>
 <p className="composer-note">{t("Attachments are private. PDF and image recognition uses your conversion allowance. Text and Word files are converted locally.")}</p></section></main>
}
