import { useEffect,useRef,useState } from 'react'
import { ArrowUp,Plus,MessageCircle,Trash2 } from 'lucide-react'
import { api,post } from './api'
type Card={id:string;title:string;authors:string;summary:string;year:string}
type Message={id:string;role:string;text:string;papers?:Card[];jobId?:string}
type Chat={id:string;title:string}
export function Agent({signedIn,login,notify}:{signedIn:boolean;login:()=>void;notify:(s:string)=>void}) {
 const [chats,setChats]=useState<Chat[]>([]),[chat,setChat]=useState(''),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false)
 const end=useRef<HTMLDivElement>(null)
 const list=()=>api<{chats:Chat[]}>('/chats').then(r=>setChats(r.chats))
 useEffect(()=>{if(signedIn)void list().catch(e=>notify(e.message))},[signedIn])
 useEffect(()=>{if(!chat)return;let active=true;const update=()=>api<{messages:Message[];pending:{status:string}[];agent:{online:boolean}}>(`/chats/${chat}`).then(r=>{if(active){setMessages(r.messages);setStatus(r.pending[0]?(r.agent.online?r.pending[0].status:'Your request is saved. Waiting for the paper agent…'):'')}}).catch(e=>{if(active)notify(e.message)});void update();const timer=setInterval(update,2500);return()=>{active=false;clearInterval(timer)}},[chat])
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages.length,status])
 const send=async(text=draft)=>{if(!signedIn){login();return}if(!text.trim()||busy||status)return;setBusy(true);try{let id=chat;if(!id){const r=await post<{chat:Chat}>('/chats',{});id=r.chat.id;setChat(id)}await post(`/chats/${id}/messages`,{text});setMessages(v=>[...v,{id:crypto.randomUUID(),role:'user',text}]);setDraft('');setStatus('Waiting for the paper agent');await list()}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 return <main className="agent-layout"><aside className="chat-history"><button className="secondary" onClick={()=>{setChat('');setMessages([]);setStatus('')}}><Plus size={20}/> New conversation</button><h2>Conversations</h2>{chats.map(c=><div className="history-row" key={c.id}><button className={chat===c.id?'selected':''} onClick={()=>setChat(c.id)}>{c.title}</button><button aria-label={`Delete ${c.title}`} onClick={async()=>{if(!confirm('Delete this conversation?'))return;try{await api(`/chats/${c.id}`,{method:'DELETE'});if(chat===c.id){setChat('');setMessages([])}await list()}catch(e){notify((e as Error).message)}}}><Trash2 size={16}/></button></div>)}</aside><section className="agent-conversation"><div className="agent-messages">{!messages.length&&<div className="agent-welcome"><MessageCircle size={40}/><h1>What are you curious about?</h1><p>Find a paper. Follow a question.<br/>Bring the useful ones into your reading library.</p>{['Find open papers about quantum entanglement','Help me find research on language learning'].map(s=><button className="suggestion" key={s} onClick={()=>void send(s)}>{s}</button>)}</div>}{messages.map(m=><div key={m.id} className={`chat-message ${m.role}`}><strong>{m.role==='user'?'You':'OnlyIdeas'}</strong><p>{m.text}</p>{m.role==='assistant' && <button className="text-button" onClick={async()=>{const reason=prompt('What concerns you about this AI response?');if(reason)try{await post('/reports',{context:`Agent message ${m.id} in conversation ${chat}`,reason});notify('Report sent for review.')}catch(e){notify((e as Error).message)}}}>Report response</button>}{m.papers?.map(p=><article className="agent-paper" key={p.id}><span>{p.year} · Open paper</span><h3>{p.title}</h3><p>{p.authors}</p><details><summary>Read abstract</summary><p>{p.summary}</p></details><button className="primary" onClick={async()=>{try{await post(`/chats/${chat}/import`,{paperId:p.id});notify('Paper queued. Follow its conversion in Your requests.')}catch(e){notify((e as Error).message)}}}>Convert &amp; add</button></article>)}</div>)}{status&&<p className="agent-progress" role="status">{status}</p>}<div ref={end}/></div><form className="chat-composer" onSubmit={e=>{e.preventDefault();void send()}}><textarea aria-label="Message the paper agent" placeholder="Ask a question or paste a paper link…" rows={2} maxLength={4000} value={draft} onChange={e=>setDraft(e.target.value)}/><button className="primary" aria-label="Send message" disabled={busy||!!status||!draft.trim()}><ArrowUp size={24}/></button></form><p className="composer-note">Paper search and downloads run on the connected research agent. Conversion uses your shared page allowance.</p></section></main>
}
