import {consentHeaders,materialKey} from './sharing-consent'
import { useEffect,useRef,useState } from 'react'
import { ArrowUp,ArrowDown,Plus,MessageCircle,Trash2,Paperclip,X,FileText } from 'lucide-react'
import { api,post,type Attachment,type Paper,type Artifact } from './api'
import { request } from './native'
import { t, currentLanguage } from './i18n'
import {authorizeImport,SharingOptions} from './Credits'
import {UploadPaper} from './UploadPaper'
import {ReaderContent} from './ReaderContent'
type Card={paperId?:string;source?:string;pdfUrl?:string;id:string;title:string;authors:string;summary:string;year:string;journal?:string}
type Action={id:string;kind:string;state:string;message:string;title?:string;jobId?:string;paperId?:string;artifactId?:string;canUpload?:boolean;sharing?:string}
type Message={id:string;role:string;text:string;papers?:Card[];jobId?:string;attachments?:Attachment[];actions?:Action[]}
type Chat={id:string;title:string}
export function Agent({accountId,signedIn,login,notify,openPaper,viewJobs,hasJobs,initialRequest,consumed}:{accountId?:string;signedIn:boolean;login:()=>void;notify:(s:string)=>void;openPaper:(id:string)=>void;viewJobs:()=>void;hasJobs:boolean;initialRequest?:{id:string;text:string};consumed:()=>void}) {
 const [chats,setChats]=useState<Chat[]>([]),[chat,setChat]=useState(''),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[files,setFiles]=useState<Attachment[]>([])
 const [awayFromLatest,setAwayFromLatest]=useState(false)
 const scroller=useRef<HTMLDivElement>(null), follow=useRef(true), touchY=useRef(0), restored=useRef(false),picker=useRef<HTMLInputElement>(null),identity=useRef(0)
 const chatKey='onlyideas:last-chat:'+accountId
 const list=()=>api<{chats:Chat[]}>('/chats').then(r=>{setChats(r.chats);return r.chats})
 const remember=(id:string)=>{localStorage.setItem(chatKey,id||'new');setChat(id);follow.current=true;restored.current=false}
 async function resume(){const rows=await list(),saved=localStorage.getItem(chatKey);return saved==='new'?'':rows.find(c=>c.id===saved)?.id||rows[0]?.id||''}
 useEffect(()=>{const epoch=++identity.current;setMessages([]);setFiles([]);setChat('');if(signedIn)void resume().then(id=>{if(epoch===identity.current)setChat(previous=>previous||id)}).catch(e=>notify(e.message));else setChats([]);return()=>{identity.current++}},[accountId])
 useEffect(()=>{if(!chat)return;let active=true;const update=()=>api<{messages:Message[];pending:{status:string}[];agent:{online:boolean}}>(`/chats/${chat}`).then(r=>{if(active){setMessages(r.messages);setStatus(r.pending[0]?(r.agent.online?r.pending[0].status:'Your request is saved. Waiting for the paper agent…'):'')}}).catch(e=>{if(active)notify(e.message)});void update();const timer=setInterval(update,2500);return()=>{active=false;clearInterval(timer)}},[chat])
 useEffect(()=>{const node=scroller.current;if(!node||!follow.current||document.querySelector('dialog[open]'))return;const id=requestAnimationFrame(()=>{node.scrollTop=node.scrollHeight;restored.current=true});return()=>cancelAnimationFrame(id)},[messages.at(-1)?.id,chat])
 async function upload(selected:FileList|null){
  if(!signedIn){login();return}if(!selected)return
  if(files.length+selected.length>3){notify(t('Attach up to three files.'));return}
  const epoch=identity.current;setUploading(true)
  try{for(const file of Array.from(selected)){if(file.size>20_000_000)throw Error(t('Choose a file smaller than 20 MB.'));const pdf=/\.pdf$/i.test(file.name);const permission=await authorizeImport(sharing==='shared',pdf?1:0,pdf?0:1,await materialKey(file));if(!permission||epoch!==identity.current)return;const r=await request('/api/attachments',{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream','X-File-Name':encodeURIComponent(file.name),'X-Paper-Sharing':permission.sharing,...consentHeaders(permission),'X-Credit-Limit':String(permission.creditLimit)},body:file});const data=await r.json();if(!r.ok)throw Error(data.error);if(epoch===identity.current)setFiles(previous=>previous.some(a=>a.id===data.attachment.id)?previous:[...previous,data.attachment])}}
  catch(e){notify((e as Error).message)}finally{setUploading(false);if(picker.current)picker.current.value=''}
 }
 const send=async(text=draft)=>{if(!signedIn){login();return}if((!text.trim()&&!files.length)||busy||status||uploading)return;setBusy(true);const epoch=identity.current;try{let id=chat||await resume();if(epoch!==identity.current)return;if(!id){const r=await post<{chat:Chat}>('/chats',{});id=r.chat.id;if(epoch!==identity.current)return}remember(id);follow.current=true;await post(`/chats/${id}/messages`,{text,attachments:files.map(f=>f.id),language:currentLanguage(),agentActions:true,sharing});if(epoch!==identity.current)return;setMessages(v=>[...v,{id:crypto.randomUUID(),role:'user',text:text||t('Help me understand these files.'),attachments:files}]);setFiles([]);setDraft('');setStatus(t("Waiting for the paper agent"));await list()}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 const [sharing,setSharing]=useState('shared'),[result,setResult]=useState<{paper:Paper;artifact:Artifact}|null>(null)
 const started=useRef('');useEffect(()=>{if(initialRequest&&signedIn&&started.current!==initialRequest.id){started.current=initialRequest.id;setDraft(initialRequest.text);void send(initialRequest.text);consumed()}},[initialRequest?.id,signedIn])
 async function openResult(action:Action){if(!action.artifactId){openPaper(action.paperId!);return}try{const [p,a]=await Promise.all([api<{paper:Paper}>(`/papers/${action.paperId}`),api<{artifacts:Artifact[]}>(`/papers/${action.paperId}/artifacts`)]);const artifact=a.artifacts.find(x=>x.id===action.artifactId);if(!artifact)throw Error(t('This saved result is no longer available.'));if(artifact.kind==='translation'){sessionStorage.setItem('onlyideas:reading:'+p.paper.id,artifact.language);openPaper(p.paper.id);return}setResult({paper:p.paper,artifact})}catch(e){notify((e as Error).message)}}
 return <main className="agent-layout">{result&&<ResultDialog close={()=>setResult(null)}><h2>{result.paper.title}</h2><p>{t("AI generated ·")} {result.artifact.model}</p><ReaderContent paper={{...result.paper,mmd:result.artifact.text,sections:[]}}/></ResultDialog>}
 <aside className="chat-history"><button className="secondary" onClick={()=>{identity.current++;remember('');setMessages([]);setStatus('');setFiles([])}}><Plus size={20}/> {t("New conversation")}</button><h2>{t("Conversations")}</h2>{chats.map(c=><div className="history-row" key={c.id}><button className={chat===c.id?'selected':''} onClick={()=>{setMessages([]);remember(c.id)}}>{c.title==='New conversation'?t(c.title):c.title}</button><button aria-label={t('Delete conversation')} onClick={async()=>{if(!confirm(t('Delete this conversation?')))return;try{await api(`/chats/${c.id}`,{method:'DELETE'});if(chat===c.id){remember('');setMessages([]);setStatus('')}await list()}catch(e){notify((e as Error).message)}}}><Trash2 size={16}/></button></div>)}</aside>
 <section className="agent-conversation"><div className="agent-options">{hasJobs&&<button className="text-button" onClick={viewJobs}>{t("Your requests")}</button>}<SharingOptions sharing={sharing} setSharing={setSharing}/></div><div className="agent-messages" ref={scroller} onScroll={e=>{const n=e.currentTarget;follow.current=n.scrollHeight-n.scrollTop-n.clientHeight<100;setAwayFromLatest(!follow.current)}} onTouchStart={e=>{touchY.current=e.touches[0].clientY}} onTouchMove={e=>{if(e.touches[0].clientY-touchY.current>22&&(document.activeElement instanceof HTMLTextAreaElement||document.activeElement instanceof HTMLInputElement))document.activeElement.blur()}}>
 {!messages.length&&<div className="agent-welcome"><MessageCircle size={36}/><h1>{t("What are you curious about?")}</h1><p>{t("Find a paper. Ask about your files. Follow an idea.")}</p>{['Find open papers about quantum entanglement','Help me find research on language learning'].map(s=><button className="suggestion" key={s} onClick={()=>void send(t(s))}>{t(s)}</button>)}</div>}
 {messages.map(m=><div key={m.id} className={`chat-message ${m.role}`}><strong>{m.role==='user'?t('You'):'OnlyIdeas'}</strong><p>{m.role==='assistant'?t(m.text):m.text}</p>
 {m.attachments?.map(f=><div className="attachment-chip" key={f.id}><FileText size={18}/><span>{f.name}<small>{t(f.state==='ready'?t("Ready"):f.state==='failed'?t("Could not prepare file"):t("Preparing your attachments"))}</small></span>{f.paperId&&<button className="text-button" onClick={()=>openPaper(f.paperId!)}>{t("Open paper")}</button>}</div>)}
 {m.role==='assistant'&&<button className="text-button" onClick={async()=>{const reason=prompt(t('What concerns you about this AI response?'));if(reason)try{await post('/reports',{context:`Agent message ${m.id} in conversation ${chat}`,reason});notify(t('Report sent for review.'))}catch(e){notify((e as Error).message)}}}>{t("Report response")}</button>}
 {m.jobId&&<button onClick={viewJobs}>{t('Your requests')}</button>}{m.actions?.map(a=><article key={a.id} className="agent-paper"><strong>{a.title}</strong><p role="status">{t(a.message)}</p>{a.state==='completed'&&a.paperId&&<button className="primary" onClick={()=>void openResult(a)}>{t(a.artifactId?'Open result':'Open paper')}</button>}{a.canUpload&&<UploadPaper jobId={a.jobId} shared={a.sharing==='shared'} needLogin={()=>false} notify={notify} done={viewJobs}/ >}{a.jobId&&<button onClick={viewJobs}>{t('Your requests')}</button>}</article>)}
 {m.papers?.map(p=><article className="agent-paper" key={p.id}><span>{[p.year,p.journal].filter(Boolean).join(' · ')}</span><h3>{p.title}</h3><p>{p.authors}</p><details><summary>{t("Read abstract")}</summary><p>{p.summary}</p></details>{p.paperId?<button className="primary" onClick={()=>openPaper(p.paperId!)}>{t('Open paper')}</button>:<><span className="paper-sharing-label">{t(sharing==='shared'?'Shared after review':'Only me')}</span><button className="primary" onClick={async()=>{try{const permission=await authorizeImport(sharing==='shared',1,0,await materialKey('research:'+p.id));if(!permission)return;const r=await post<{job:{paperId?:string}}>(`/chats/${chat}/import`,{paperId:p.id,...permission});if(r.job.paperId)openPaper(r.job.paperId);else viewJobs()}catch(e){notify((e as Error).message)}}}>{t("Fetch & read")}</button><UploadPaper researchId={p.id} shared={sharing==='shared'} needLogin={()=>{if(!signedIn){login();return true}return false}} notify={notify} done={viewJobs}/></>}{p.source&&<a href={p.source} target="_blank" rel="noreferrer">{t('Source')} ↗</a>}</article>)}</div>)}
 {status&&<p className="agent-progress" role="status">{t(status)}</p>}</div>
 {awayFromLatest&&<button className="agent-jump" aria-label={t("Go to latest message")} onClick={()=>{follow.current=true;scroller.current?.scrollTo({top:scroller.current.scrollHeight,behavior:'smooth'});setAwayFromLatest(false)}}><ArrowDown size={18}/>{t("Go to latest message")}</button>}
 <div className="attachment-tray">{files.map(f=><div className="attachment-chip" key={f.id}><FileText size={16}/><span>{f.name}</span><button aria-label={t("Remove attachment")} onClick={()=>setFiles(v=>v.filter(a=>a.id!==f.id))}><X size={16}/></button></div>)}{uploading&&<p role="status">{t("Uploading attachment…")}</p>}</div>
 <form className="chat-composer" onSubmit={e=>{e.preventDefault();void send()}}><input ref={picker} hidden type="file" multiple accept=".pdf,.docx,.png,.jpg,.jpeg,.webp,.txt,.md,.mmd,.csv,.json,.tex" onChange={e=>void upload(e.target.files)}/><button type="button" className="icon-button" aria-label={t("Attach files")} disabled={uploading||files.length>=3} onClick={()=>signedIn?picker.current?.click():login()}><Paperclip size={22}/></button><textarea aria-label={t("Message the paper agent")} placeholder={t("Ask a question or attach a file…")} rows={1} maxLength={4000} value={draft} onChange={e=>{setDraft(e.target.value);e.target.style.height='auto';e.target.style.height=Math.min(e.target.scrollHeight,130)+'px'}}/><button className="primary" aria-label={t("Send message")} disabled={busy||uploading||!!status||(!draft.trim()&&!files.length)}><ArrowUp size={24}/></button></form>
 </section></main>
}

function ResultDialog({close,children}:{close:()=>void;children:React.ReactNode}){const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);return <dialog ref={ref} aria-label={t('Saved results · AI generated')} onCancel={close}><div className="modal"><button className="text-button" onClick={close}>{t('Close')}</button>{children}</div></dialog>}
