import {useEffect,useRef,useState} from 'react'
import {api,post,type Paper,type Job} from './api'
import {t} from './i18n'
import {UploadPaper} from './UploadPaper'
import {PaperActions} from './PaperActions'
export type ResearchHit={id:string;title:string;authors:string;summary?:string;source:string;pdfUrl?:string;paperId?:string;year?:string;journal?:string;doi?:string;discipline?:string;subdiscipline?:string;index?:string;ref?:string;fetchUnavailable?:string}
type Discipline={id:string;name:string;children:{id:string;name:string}[]}
export function metadata(p:ResearchHit|Paper){return [p.discipline,p.subdiscipline,p.year,p.journal].filter(Boolean).join(' · ')}
export function fuzzyMatch(query:string,text:string){const words=text.toLocaleLowerCase().normalize('NFKD').replace(/\p{M}/gu,'').split(/[^\p{L}\p{N}]+/u);return query.toLocaleLowerCase().normalize('NFKD').replace(/\p{M}/gu,'').split(/\s+/).filter(Boolean).every(q=>words.some(w=>w.includes(q)||(q.length>=5&&Math.abs(w.length-q.length)<=1&&oneEdit(q,w))))}
function oneEdit(a:string,b:string){let i=0,j=0,n=0;while(i<a.length&&j<b.length){if(a[i]===b[j]){i++;j++;continue}if(++n>1)return false;if(a.length>=b.length)i++;if(b.length>=a.length)j++}return n+(a.length-i)+(b.length-j)<=1}
export function Discovery({query,setQuery,open,needLogin,notify,requests,local,saved,setSaved,ask}:{ask:(text:string)=>void;saved:boolean;setSaved:(v:boolean)=>void;local:Paper[];query:string;setQuery:(s:string)=>void;open:(p:Paper)=>void;needLogin:()=>boolean;notify:(s:string)=>void;requests:()=>void}){
 const [options,setOptions]=useState({source:'all',discipline:'',subdiscipline:'',from:'',to:'',journal:'',sort:'latest'}),[advanced,setAdvanced]=useState(false),[taxonomy,setTaxonomy]=useState<Record<string,Discipline[]>>({}),[hits,setHits]=useState<ResearchHit[]>([]),[next,setNext]=useState<number|null>(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[retry,setRetry]=useState(0),[importing,setImporting]=useState(''),[linked,setLinked]=useState<ResearchHit|null>(null);const generation=useRef(0),marker=useRef<HTMLButtonElement>(null),loading=useRef(false);
 useEffect(()=>{const id=new URLSearchParams(location.search).get('research');if(id&&/^[\w-]+$/.test(id))void api<{paper:ResearchHit}>('/discovery/item/'+id).then(r=>setLinked(r.paper)).catch(e=>setNotice(e.message))},[]);
 useEffect(()=>{const changed=()=>setRetry(n=>n+1);if(saved)window.addEventListener('onlyideas:paper-saved',changed);return()=>window.removeEventListener('onlyideas:paper-saved',changed)},[saved]);
 useEffect(()=>{const refresh=()=>setRetry(n=>n+1);window.addEventListener('onlyideas:refresh-library',refresh);return()=>window.removeEventListener('onlyideas:refresh-library',refresh)},[]);
 const key=JSON.stringify({query,options,saved,retry});const current=useRef(key);current.current=key;
 useEffect(()=>{void api<Record<string,Discipline[]>>('/discovery/taxonomy').then(setTaxonomy).catch(()=>{})},[]);
 const load=async(page=1,k=key)=>{if(loading.current)return;const epoch=generation.current;loading.current=true;setBusy(true);try{const r=saved?await api<{papers:ResearchHit[]}>('/saved'):await api<{papers:ResearchHit[];nextPage?:number;unavailable?:string[];stale?:boolean}>('/discovery?'+new URLSearchParams({...options,q:query,page:String(page)}));if(k!==current.current||epoch!==generation.current)return;setHits(old=>page===1?r.papers:[...old,...r.papers.filter(p=>!old.some(x=>x.id===p.id))]);setNext('nextPage'in r?Number(r.nextPage)||null:null);setNotice('unavailable'in r&&(r.unavailable as string[])?.length?t('Some research indexes are temporarily unavailable.'):'stale'in r&&r.stale?t('Showing cached research results.'):'')}catch(e){if(k===current.current)setNotice((e as Error).message)}finally{if(epoch===generation.current){loading.current=false;setBusy(false)}}};
 useEffect(()=>{generation.current++;loading.current=false;setNext(null);setHits([]);setNotice('');const timer=setTimeout(()=>void load(1,key),query?450:0);return()=>clearTimeout(timer)},[key]);
 useEffect(()=>{if(!marker.current||!next||busy||notice)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))void load(next)},{rootMargin:'200px'});observer.observe(marker.current);return()=>observer.disconnect()},[next,busy,key,notice]);
 async function select(p:ResearchHit){if(p.paperId||(!p.ref?.startsWith('r-')&&p.ref)){open({id:p.paperId||p.ref}as Paper);return}if(needLogin())return;setImporting(p.id);try{const r=await post<{paperId?:string;job?:Job}>('/discovery/import',{id:p.id,sharing:'shared'});if(r.paperId)open({id:r.paperId}as Paper);else{notify(t('Fetching paper. Conversion progress is saved to your requests.'));requests()}}catch(e){notify((e as Error).message);requests()}finally{setImporting('')}}
 const fields=taxonomy[options.source==='arxiv'?'arxiv':'openalex']||[],children=fields.find(d=>d.id===options.discipline)?.children||[];
 return <section className="discovery"><div className="discovery-heading"><div><span className="eyebrow">OnlyIdeas</span><h1>{t(saved?'Saved':query?'Search research':'Research for you')}</h1></div><button className="secondary" onClick={()=>{if(!saved&&needLogin())return;setSaved(!saved)}}>{t(saved?'Research for you':'Saved')}</button></div><label className="research-search"><span>⌕</span><input aria-label={t('Search all research')} placeholder={t('Find a paper or ask to fetch it…')} value={query} onChange={e=>{setQuery(e.target.value);setOptions({...options,sort:e.target.value?'relevance':'latest'})}}/><button aria-label={t('Ask the agent')} disabled={!query.trim()} onClick={()=>ask(query)}>↑</button>{!saved&&<button onClick={()=>setAdvanced(!advanced)} aria-expanded={advanced}>{t('Filters')}</button>}</label>
 {advanced&&!saved&&<div className="research-filters"><label>{t('Source')}<select aria-label={t("Source")} value={options.source} onChange={e=>setOptions({...options,source:e.target.value,discipline:'',subdiscipline:''})}>{[['all','All research'],['openalex','OpenAlex'],['arxiv','arXiv']].map(([v,n])=><option key={v} value={v}>{t(n)}</option>)}</select></label><label>{t('Primary discipline')}<select aria-label={t("Primary discipline")} value={options.discipline} onChange={e=>setOptions({...options,discipline:e.target.value,subdiscipline:''})}><option value="">{t('All disciplines')}</option>{fields.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>{t('Secondary discipline')}<select aria-label={t("Secondary discipline")} value={options.subdiscipline} disabled={!children.length} onChange={e=>setOptions({...options,subdiscipline:e.target.value})}><option value="">{t('All disciplines')}</option>{children.map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label>{(['from','to','journal']as const).map(k=><label key={k}>{t({from:'From year',to:'To year',journal:'Journal'}[k])}<input aria-label={t({from:"From year",to:"To year",journal:"Journal"}[k])} inputMode={k==='journal'?'text':'numeric'} value={options[k]} maxLength={k==='journal'?120:4} onChange={e=>setOptions({...options,[k]:e.target.value})}/></label>)}<label>{t('Sort')}<select aria-label={t("Sort")} value={options.sort} onChange={e=>setOptions({...options,sort:e.target.value})}><option value="latest">{t('Newest first')}</option><option value="relevance">{t('Relevance')}</option></select></label><button onClick={()=>{setOptions({source:'all',discipline:'',subdiscipline:'',from:'',to:'',journal:'',sort:query?'relevance':'latest'})}}>{t('Clear filters')}</button></div>}
 {!saved&&query&&local.length>0&&<div className="local-results"><h2>{t('Reading library')}</h2>{local.slice(0,5).map(p=><button className="research-title" key={p.id} onClick={()=>open(p)}>{p.title} ↗</button>)}</div>}
 <p className="muted discovery-help">{t('Tap a paper to fetch and convert it. Existing papers open immediately. Shared imports enter publication review.')}</p>
 <div className="research-list">{(linked&&!saved?[linked,...hits.filter(p=>p.id!==linked.id)]:hits).filter(p=>!saved||fuzzyMatch(query,`${p.title} ${p.authors} ${metadata(p)} ${p.doi||''}`)).map(p=><article className="research-card" key={p.id}><div className="research-meta">{metadata(p)||[p.index,p.year].filter(Boolean).join(' · ')}</div><button className="research-title" disabled={importing===p.id} onClick={()=>void select(p)}>{p.title}</button><p className="research-authors">{p.authors}</p>{p.fetchUnavailable&&<p className="notice">{t(p.fetchUnavailable)}</p>}{p.summary&&<p className="research-summary">{p.summary}</p>}<div className="research-source"><span>{p.doi?'DOI '+p.doi:p.index}</span><a href={p.source} target="_blank" rel="noreferrer">{t('Source')} ↗</a></div><button className="research-open" disabled={importing===p.id} onClick={()=>void select(p)}>{t(importing===p.id?'Adding your paper…':(p.paperId||(p.ref&&!p.ref.startsWith('r-')))?'Open paper':'Fetch & read')} →</button>{!p.paperId&&(!p.ref||p.ref.startsWith('r-'))&&<UploadPaper researchId={p.id} needLogin={needLogin} notify={notify} done={requests}/>}<PaperActions reference={p.ref||'r-'+p.id} title={p.title} needLogin={needLogin} notify={notify}/></article>)}</div>
 {notice&&<p role="status">{t(notice)} <button onClick={()=>setRetry(retry+1)}>{t('Try again')}</button></p>}{!busy&&!hits.length&&!notice&&<p>{t('No papers found. Try broader keywords or fewer filters.')}</p>}{busy&&<p role="status">{t('Finding research…')}</p>}{next&&<button ref={marker} className="secondary" disabled={busy} onClick={()=>void load(next)}>{t('Load more')}</button>}
 </section>
}
