import {useEffect,useRef,useState} from 'react'
import {createPortal} from 'react-dom'
import {api,post,type Comment} from './api'
import {t} from './i18n'
import {Bookmark,Heart,MessageCircle,Share2} from 'lucide-react'
type Social={saved:boolean;liked:boolean;likes:number;commentCount:number;shareUrl:string|null;private:boolean}
export function PaperActions({reference,title,needLogin,notify}:{reference:string;title:string;needLogin:()=>boolean;notify:(s:string)=>void}){
 const [state,setState]=useState<Social>(),[open,setOpen]=useState(false),[comments,setComments]=useState<Comment[]>([]),[draft,setDraft]=useState(''),[terms,setTerms]=useState(false),[busy,setBusy]=useState(false),[scroll,setScroll]=useState(0);const panel=useRef<HTMLDivElement>(null);
 const load=()=>api<Social>('/items/'+reference).then(setState).catch(()=>{});
 useEffect(()=>{void load()},[reference]);
 async function toggle(k:'saved'|'liked'){if(needLogin()||busy)return;setBusy(true);try{setState(await api<Social>('/items/'+reference,{method:'PUT',body:JSON.stringify({[k]:!state?.[k]})}))}catch(e){notify((e as Error).message)}finally{setBusy(false)}}
 const loadComments=async()=>{try{setComments((await api<{comments:Comment[]}>('/items/'+reference+'/comments')).comments);setScroll(x=>x+1)}catch(e){notify((e as Error).message)}};
 useEffect(()=>{if(!open)return;void loadComments();const previous=document.body.style.overflow;document.body.style.overflow='hidden';const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};document.addEventListener('keydown',escape);return()=>{document.body.style.overflow=previous;document.removeEventListener('keydown',escape)}},[open]);useEffect(()=>{if(open&&panel.current)panel.current.scrollTop=panel.current.scrollHeight},[scroll,open]);
 async function share(){if(!state?.shareUrl){notify(t('Private papers can only be opened by their owner.'));return}try{if(navigator.share)await navigator.share({title,url:state.shareUrl});else{await navigator.clipboard.writeText(state.shareUrl);notify(t('Paper link copied.'))}}catch(e){if((e as Error).name!=='AbortError')notify((e as Error).message)}}
 return <><div className="paper-item-actions"><button aria-pressed={!!state?.saved} disabled={busy} onClick={()=>void toggle('saved')}><Bookmark size={16} aria-hidden="true" fill={state?.saved?"currentColor":"none"}/> {t(state?.saved?'Saved':'Save')}</button><button aria-pressed={!!state?.liked} disabled={busy} onClick={()=>void toggle('liked')}><Heart size={16} aria-hidden="true" fill={state?.liked?"currentColor":"none"}/> {t('Like')}{state?.likes?' '+state.likes:''}</button><button onClick={()=>setOpen(true)}><MessageCircle size={16} aria-hidden="true"/> {t('Comment')}{state?.commentCount?' '+state.commentCount:''}</button><button onClick={()=>void share()}><Share2 size={16} aria-hidden="true"/> {t('Share')}</button></div>
 {open&&createPortal(<div className="item-modal-backdrop"><section className="modal item-discussion" role="dialog" aria-modal="true" aria-label={t('Paper discussion')}><header><h2>{t('Paper discussion')}</h2><button aria-label={t('Close')} onClick={()=>setOpen(false)}>×</button></header><h3>{title}</h3><div className="item-comments" ref={panel}>{comments.map(c=><article key={c.id}><strong>{c.author}</strong><p>{c.text}</p>{c.pending&&<small>{t('Waiting for community review')}</small>}{c.canDelete?<button onClick={async()=>{await api('/comments/'+c.id,{method:'DELETE'});void loadComments()}}>{t('Delete')}</button>:<><button onClick={async()=>{if(needLogin())return;const reason=prompt(t('What should we review?'));if(reason)try{await post('/comments/'+c.id+'/report',{reason});notify(t('Report sent.'))}catch(e){notify((e as Error).message)}}}>{t('Report')}</button><button onClick={async()=>{if(needLogin())return;try{await post('/comments/'+c.id+'/block',{});void loadComments()}catch(e){notify((e as Error).message)}}}>{t('Block reader')}</button></>}</article>)}{!comments.length&&<p>{t('What caught your attention? Leave the first thought.')}</p>}{!state?.private&&<label><input type="checkbox" checked={terms} onChange={e=>setTerms(e.target.checked)}/>{t('I accept the Community Terms')} · <a href="https://lachlan.lazying.art/OnlyIdeasApp/terms.html" target="_blank" rel="noreferrer">{t('Read Community Terms')}</a></label>}<textarea aria-label={t('Your comment')} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={5000}/><button className="primary" disabled={busy||!draft.trim()||(!state?.private&&!terms)} onClick={async()=>{if(needLogin())return;setBusy(true);try{await post('/items/'+reference+'/comments',{id:crypto.randomUUID(),text:draft,acceptTerms:terms});setDraft('');await loadComments();void load()}catch(e){notify((e as Error).message)}finally{setBusy(false)}}}>{t('Post thought')}</button></div></section></div>,document.body)}
 </>
}
