import {useEffect,useState} from 'react'
import {api,post,type Paper,type Artifact,type Job} from './api'
import {t,languageNames} from './i18n'
type Piece={id:string;text:string;display?:string;sentences:{id:string;text:string;display?:string}[]}
export function PieceTranslation({paper,language,quote,needLogin,notify,onLanguageChange,onOpen}:{onOpen:(language:string)=>void;paper:Paper;language:string;quote:string;needLogin:()=>boolean;notify:(s:string)=>void;onLanguageChange:(s:string)=>void}) {
 const [pieces,setPieces]=useState<Piece[]>([]),[paragraph,setParagraph]=useState(''),[sentence,setSentence]=useState(''),[artifacts,setArtifacts]=useState<Artifact[]>([]),[pending,setPending]=useState(false),[job,setJob]=useState(''),[error,setError]=useState('')
 const selected=pieces.find(p=>p.id===paragraph),id=sentence||paragraph,ready=artifacts.find(a=>a.kind==='translation'&&a.language===language&&a.segmentId===id)
 async function load(){const r=await api<{artifacts:Artifact[]}>(`/papers/${paper.id}/artifacts`);setArtifacts(r.artifacts)}
 useEffect(()=>{let active=true;api<{segments:Piece[]}>(`/papers/${paper.id}/segments`).then(r=>{if(!active)return;setPieces(r.segments);setParagraph((r.segments.find(p=>quote&&p.text.replace(/\s+/g,' ').includes(quote.slice(0,80)))||r.segments[0])?.id||'')}).catch(e=>setError(e.message));void load().catch(e=>setError(e.message));return()=>{active=false}},[paper.id])
 useEffect(()=>{if(!job)return;const timer=setInterval(()=>void load().catch(()=>{}),3000);return()=>clearInterval(timer)},[job,paper.id])
 useEffect(()=>{if(ready)setJob('')},[ready])
 return <section className="piece-translation"><h3>{t('Translate a paragraph or sentence')}</h3><p className="muted">{t('Only missing pieces use the model. Saved translations are reused.')}</p>{error&&<p role="alert">{error}</p>}<label>{t('Read in')}<select value={language} onChange={e=>onLanguageChange(e.target.value)}>{Object.entries(languageNames).map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label>{t('Paragraph')}<select value={paragraph} onChange={e=>{setParagraph(e.target.value);setSentence('')}}>{pieces.map((p,i)=><option key={p.id} value={p.id}>{i+1}. {(p.display||p.text).slice(0,85)}</option>)}</select></label><label>{t('Sentence')}<select value={sentence} onChange={e=>setSentence(e.target.value)}><option value="">{t('Entire paragraph')}</option>{selected?.sentences.filter(s=>s.text.trim()).map((s,i)=><option key={s.id} value={s.id}>{i+1}. {(s.display||s.text).slice(0,85)}</option>)}</select></label>{selected&&<details><summary>{t('This passage')}</summary><blockquote>{sentence?(selected.sentences.find(s=>s.id===sentence)?.display||selected.sentences.find(s=>s.id===sentence)?.text):(selected.display||selected.text)}</blockquote></details>}{ready?<button className="secondary" onClick={()=>onOpen(language)}>{t('Open in reader')}</button>:<button className="secondary" disabled={!id||pending} onClick={async()=>{if(needLogin())return;setPending(true);try{const r=await post<{job:Job}>(`/papers/${paper.id}/assist`,{kind:'translation',language,segmentId:id});setJob(r.job.id);await load();notify(t(r.job.state==='failed'?r.job.message:'Translation requested. Existing work is reused.'))}catch(e){notify((e as Error).message)}finally{setPending(false)}}}>{t(job?'Refresh results':'Translate this passage')}</button>}</section>
}
