import {useEffect,useState,useRef} from 'react'
import {api,post,type Paper} from './api'
import {PaperActions} from './PaperActions'
import {metadata,type ResearchHit} from './Discovery'
import {t,languageNames} from './i18n'
type Preferences={interests:string;discipline:string;language:string;dailyEnabled:boolean;dailyTime:string;timezone:string;commentAlerts:boolean;likeAlerts:boolean}
type EventItem={id:string;kind:string;created:number;ref:string;title:string;actor?:string;read?:boolean;active?:boolean;message?:string;state?:string;paperId?:string;source?:string}
export function ReadingSpace({open,needLogin,notify,requests,signedIn}:{signedIn:boolean;open:(p:Paper)=>void;needLogin:()=>boolean;notify:(s:string)=>void;requests:()=>void}){
 const request=useRef(0);const [tab,setTab]=useState('saved'),[papers,setPapers]=useState<ResearchHit[]>([]),[events,setEvents]=useState<EventItem[]>([]),[prefs,setPrefs]=useState<Preferences>(),[fields,setFields]=useState<{id:string;name:string}[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState(false),[unread,setUnread]=useState(0)
 async function load(){if(!signedIn)return;const sequence=++request.current;setLoading(true);setError('');try{const r=await api<{papers?:ResearchHit[];events?:EventItem[];notifications?:EventItem[];unread?:number}>('/'+tab);if(sequence!==request.current)return;setPapers(r.papers||[]);setEvents(r.events||r.notifications||[]);if(r.unread!==undefined)setUnread(r.unread)}catch(e){if(sequence===request.current)setError((e as Error).message)}finally{if(sequence===request.current)setLoading(false)}}
 useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load()},30000);return()=>{request.current++;clearInterval(timer)}},[tab,signedIn])
 useEffect(()=>{if(!signedIn)return;void api<{preferences:Preferences}>('/preferences').then(r=>setPrefs(r.preferences)).catch(e=>setError(e.message));void api<{openalex:{id:string;name:string}[]}>('/discovery/taxonomy').then(r=>setFields(r.openalex)).catch(()=>{})},[signedIn])
 async function choose(p:ResearchHit){if(p.paperId||(p.ref&&!p.ref.startsWith('r-'))){open({id:p.paperId||p.ref}as Paper);return}if(needLogin())return;try{const r=await post<{paperId?:string}>('/discovery/import',{id:p.id,sharing:'shared'});if(r.paperId)open({id:r.paperId}as Paper);else requests()}catch(e){notify((e as Error).message)}}
 const name=(k:string)=>({saved:'Saved',liked:'Liked',inbox:'Inbox',activity:'Activity',daily:'For you'}[k]||k)
 if(!signedIn)return <main className="reading-space"><h1>{t('Your space')}</h1><p>{t('Sign in to keep your papers and conversations together.')}</p><button className="primary" onClick={needLogin}>{t('Sign in')}</button></main>
 return <main className="reading-space"><div className="discovery-heading"><h1>{t('Your space')}</h1><button className="secondary" onClick={()=>setSettings(!settings)}>{t('Interests & notifications')}</button></div><div className="space-tabs">{['saved','liked','inbox','activity','daily'].map(k=><button className={tab===k?'selected':''} key={k} onClick={()=>setTab(k)}>{t(name(k))}{k==='inbox'&&unread>0?' · '+unread:''}</button>)}</div>
 {settings&&prefs&&<section className="space-settings"><h2>{t('Interests & notifications')}</h2><label>{t('Topics you enjoy')}<input value={prefs.interests} maxLength={120} placeholder={t('For example: quantum physics')} onChange={e=>setPrefs({...prefs,interests:e.target.value})}/></label><label>{t('Primary discipline')}<select value={prefs.discipline} onChange={e=>setPrefs({...prefs,discipline:e.target.value})}><option value="">{t('All disciplines')}</option>{fields.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label><label>{t('Preferred reading language')}<select value={prefs.language} onChange={e=>setPrefs({...prefs,language:e.target.value})}>{Object.entries(languageNames).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select></label>{[['dailyEnabled','Daily reading reminder'],['commentAlerts','Comment notifications'],['likeAlerts','Like notifications']].map(([k,n])=><label className="check-label" key={k}><input type="checkbox" checked={!!prefs[k as keyof Preferences]} onChange={e=>setPrefs({...prefs,[k]:e.target.checked})}/>{t(n)}</label>)}<label>{t('Daily time')}<input type="time" value={prefs.dailyTime} onChange={e=>setPrefs({...prefs,dailyTime:e.target.value})}/></label><p className="muted">{t('Daily reminders are delivered by the native app. Activity appears in your inbox.')} · {prefs.timezone}</p><button className="primary" onClick={async()=>{try{const r=await api<{preferences:Preferences}>('/preferences',{method:'PUT',body:JSON.stringify({...prefs,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone})});setPrefs(r.preferences);notify(t('Preferences saved'));void load()}catch(e){notify((e as Error).message)}}}>{t('Save preferences')}</button></section>}
 {error&&<p role="alert">{error} <button onClick={()=>void load()}>{t('Try again')}</button></p>}{loading&&<p role="status">{t('Loading…')}</p>}
 {tab==='inbox'&&events.some(e=>!e.read)&&<button className="secondary" onClick={async()=>{await api('/inbox',{method:'PUT',body:JSON.stringify({ids:events.map(e=>e.id)})});void load()}}>{t('Mark all read')}</button>}
 <div className="research-list">{papers.map(p=><article className="research-card" key={p.id}><span className="research-meta">{metadata(p)}</span><button className="research-title" onClick={()=>void choose(p)}>{p.title}</button><p className="research-authors">{p.authors}</p><button onClick={()=>void choose(p)}>{t(p.paperId||(p.ref&&!p.ref.startsWith('r-'))?'Open paper':'Fetch & read')}</button><PaperActions reference={p.ref||'r-'+p.id} title={p.title} needLogin={needLogin} notify={notify}/></article>)}</div>
 <div className="activity-list">{events.map(e=><article key={e.id} className={e.read===false?'unread':''}><div><strong>{t(e.kind==='comment'?'New comment':e.kind==='like'?'New like':e.kind==='fetch'?'Paper request':e.kind==='saved'?(e.active?'Saved':'Removed from Saved'):(e.active?'Liked':'Removed from Liked'))}</strong><time>{new Date(e.created).toLocaleString()}</time></div><h3>{e.title}</h3>{e.actor&&<p>{e.actor}</p>}{e.message&&<p>{t(e.message)}</p>}{e.ref&&<button onClick={async()=>{if(e.read===false)await api('/inbox',{method:'PUT',body:JSON.stringify({ids:[e.id]})});if(e.ref.startsWith('r-')){const r=await api<{paper:ResearchHit}>('/discovery/item/'+e.ref.slice(2));setPapers([r.paper]);}else open({id:e.ref}as Paper)}}>{t('Open paper')}</button>}{e.kind==='fetch'&&!e.paperId&&<button onClick={requests}>{t('Your requests')}</button>}</article>)}</div>
 {!loading&&!error&&!papers.length&&!events.length&&<p className="space-empty">{t(tab==='inbox'?'No new notifications':tab==='activity'?'Your reading activity will appear here.':'No papers here yet.')}</p>}
 </main>
}
