import{useEffect,useState,useRef}from'react'
import{api,post}from'./api'
import{native}from'./native'
import{t}from'./i18n'
type Catalog={enabled:boolean;newPurchaseEnabled?:boolean;providers:{stripe:boolean};canSubscribe:boolean;trialEligible:boolean;plan:string|null;subscriptions:{platform:string;state:string;expires:number}[];plans:{id:string;name:string;targetUSD:string;credits:number;pages:number;fetches:number;agentTurns:number}[];quota:null|{enabled:boolean;unlimited:boolean;remainingPages:number;remainingFetches:number;ends:number}}
export function Subscriptions(){
 const current=useRef(true),request=useRef(0),working=useRef(false)
 const[catalog,setCatalog]=useState<Catalog>(),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{current.current=true;const load=()=>{const id=++request.current;return api<Catalog>('/billing').then(c=>{if(current.current&&id===request.current){setCatalog(c);setError('')}}).catch(()=>{if(current.current&&id===request.current)setError('Unable to load plans. Try again.')})};if(new URLSearchParams(window.location.search).get('billing')==='success')void post('/billing/restore',{}).then(()=>{if(current.current)void load()}).catch(()=>{});void load();const interval=setInterval(()=>{if(!working.current)void load()},15_000);return()=>{current.current=false;request.current++;clearInterval(interval)}},[])
 async function restore(){working.current=true;setBusy(true);setError('');const id=++request.current;try{const result=await post<Catalog>('/billing/restore',{});if(current.current&&id===request.current)setCatalog(result)}catch(e){if(current.current)setError((e as Error).message)}finally{working.current=false;if(current.current)setBusy(false)}}
 if(native)return null
 const available=!!catalog?.enabled&&catalog.providers.stripe
 async function open(action:string,plan?:string){working.current=true;request.current++;setBusy(true);setError('');try{const result=await post<{url:string}>('/billing/'+action,{plan});if(!current.current)return;const url=new URL(result.url);if(!['https://checkout.stripe.com','https://billing.stripe.com'].includes(url.origin))throw Error('Invalid payment destination');window.location.assign(url.href)}catch(e){working.current=false;if(current.current){setError((e as Error).message);setBusy(false)}}}
 return <details className="subscription-panel"><summary><strong>{t('Plans & usage')}</strong><span>{t('View plans')}</span></summary><h2>{t('Monthly plans')}</h2><p>{t('Existing papers and cached translations are free to read. Plans cover new fetching and transcription.')}</p>{!available&&<p role="status">{t('Subscriptions are coming soon. You can keep reading for free.')}</p>}{catalog?.quota?.enabled&&<p><strong>{catalog.quota.unlimited?t('Unlimited owner allowance'):t('{pages} transcription pages and {fetches} fetches remaining',{pages:catalog.quota.remainingPages,fetches:catalog.quota.remainingFetches})}</strong>{!catalog.quota.unlimited&&<small>{t('Renews on {date}',{date:new Date(catalog.quota.ends).toLocaleDateString()})}</small>}</p>}<div className="subscription-grid">{catalog?.plans.map(plan=><article key={plan.id}><h3>{t(plan.name)}</h3><strong>{t(available?'{price} / month':'Planned price: {price} / month',{price:new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(Number(plan.targetUSD))})}</strong><p>{t('{pages} transcription pages · {fetches} new-paper fetches per month',{pages:plan.pages,fetches:plan.fetches})}</p><p>{t('{credits} credits each month · {messages} agent messages daily',{credits:plan.credits,messages:plan.agentTurns})}</p>{available&&catalog.trialEligible&&<p className="fine">{t('7 days free, then {price} per month. Trial includes 50 pages and 10 fetches. Cancel before it ends to avoid payment.',{price:'US$'+plan.targetUSD})}</p>}<button className="primary" disabled={busy||!available||catalog.newPurchaseEnabled!==true} onClick={()=>void open('checkout',plan.id)}>{t(!available?'Coming soon':catalog.plan===plan.id?'Current plan':catalog.trialEligible?'Start 7-day free trial':'Subscribe')}</button></article>)}</div>{available&&catalog?.subscriptions.some(s=>s.platform==='stripe')&&<button className="secondary" disabled={busy} onClick={()=>void open('portal')}>{t('Manage subscription')}</button>}{available&&<button className="text-button" disabled={busy} onClick={()=>void restore()}>{t('Restore purchases')}</button>}{error&&<p role="alert">{t(error)}</p>}{!available&&<p className="fine">{t('Eligible subscribers get a 7-day trial when plans become available.')}</p>}<p className="fine">{t('Subscriptions renew monthly until canceled. Monthly quotas reset; unused credits do not expire.')} <a href="/terms.html">{t('Terms')}</a> · <a href="/privacy.html">{t('Privacy')}</a></p></details>
}
